### ISSUE TITLE
There was a problem while trying to compile the sample c++ file into an .exe file

### ISSUE THREAD

**Issue by hunter1992** [ikorotkin/dae-cpp#14]
Hi @ikorotkin, 
After cloning the dae-cpp package, I bulid the solution using Visual Studio, and got 3 sample .exe files( robertson.exe, perovskite.exe or diffusion_2d.exe) . The Comparison of running results with Matlab is encouraging.
I'm not familiar with C++, but as I understand, If I construct a C++ file (for example, the robertson.cpp) which can describe my DAEs, I can compile it using cl command or g++ command, right? But when I compile the robertson.cpp in "Developer PowerShell for VS 2019" using cl command, I got some problems:

> cl .\robertson.cpp
......
......

/out:robertson.exe
robertson.obj
**robertson.obj : error LNK2001**: Unresolved external symbol "public: virtual void __thiscall daecpp::Jacobian::operator()(struct daecpp::sparse_matrix_holder &,class std::vector<float,class std::allocator<float> > const &,double)" (??RJacobian@daecpp@@UAEXAAUsparse_matrix_holder@1@ABV?$vector@MV?$allocator@M@std@@@std@@N@Z)
**robertson.obj : error LNK2019**: Unresolved external symbol "public: __thiscall daecpp::Solver::Solver(class daecpp::RHS &,class daecpp::Jacobian &,class daecpp::MassMatrix &,class daecpp::SolverOptions &)" (??0Solver@daecpp@@QAE@AAVRHS@1@AAVJacobian@1@AAVMassMatrix@1@AAVSolverOptions@1@@Z)，该符号在函数 "public: __thiscall MySolver::MySolver(class daecpp::RHS &,class daecpp::Jacobian &,class daecpp::MassMatrix &,class daecpp::SolverOptions &)" (??0MySolver@@QAE@AAVRHS@daecpp@@AAVJacobian@2@AAVMassMatrix@2@AAVSolverOptions@2@@Z) 中被引用
**robertson.obj : error LNK2019**: Unresolved external symbol "public: virtual __thiscall daecpp::Solver::~Solver(void)" (??1Solver@daecpp@@UAE@XZ)，该符号在函数 "public: virtual __thiscall MySolver::~MySolver(void)" (??1MySolver@@UAE@XZ) 中被引用
**robertson.obj : error LNK2019**: Unresolved external symbol "public: int __thiscall daecpp::Solver::operator()(class std::vector<float,class std::allocator<float> > &,double &)" (??RSolver@daecpp@@QAEHAAV?$vector@MV?$allocator@M@std@@@std@@AAN@Z)，该符号在函数 _main  中被引用
robertson.exe : fatal error LNK1120: 4 Unresolved external symbol

I searched on the internet "Unresolved external symbol" error maybe caused by wrong head files configuration. But I checked my system INCLUDE, LIB, and PATH parameter surely has mkl_types.h file which is need.
So, my issue may be a little stupid, I would like to ask you more details of using the dae-cpp after i already construct my DAEs description C++ file.
Thanks a lot!
Best Wishes

**Comment by ikorotkin** [comment]
Hi @hunter1992,

Sure you can compile your cpp-file with your custom DAE using `cl` or `g++`, but you need to be sure `dae-cpp` library is linked to the project. From the error messages, one can conclude that the compiler could not find any of the functions from `dae-cpp` library. It wasn't linked.

If you managed to compile `perovskite.exe`, `diffusion_2d.exe`, etc. in Visual Studio, `dae-cpp` library should be compiled as well (look for `dae-cpp.lib` in `Release` folder). Then add it to the command line with `cl`, for example:

```
cl robertson.cpp dae-cpp.lib /EHsc /MD`
```

Will it work?

**Comment by hunter1992** [comment]
Hi @ikorotkin, the problem was solved. Thank you very much!
You are right, the problem is with the linking of the static library. I finally give up the PowerShell, and constructed a project in Visual Studio, the key of solving the trouble is seting the lib name and path in project properties. So, what I lack is getting familiar with the using of the Visual Studio.
Thank you! I 'm gonna leran the example cpp files to trans my DAEs to code implement.
