### ISSUE TITLE
./../../src/typedefs.h:7:10: fatal error: 'mkl_types.h' file not found

### ISSUE THREAD

**Issue by viviane-git** [ikorotkin/dae-cpp#15]
Hi ikorotkin, 

I tried to run your examples but for all the same error occurs
"./../../src/typedefs.h:7:10: fatal error: 'mkl_types.h' file not found"

Indeed, in your whole repro no file named "mkl_types.h" exists. Can you add the missing file to your repro please? or am I doing something wrong?

Thanks!

**Comment by ikorotkin** [comment]
Hi @viviane-git,

The file named `mkl_types.h` is a part of Intel MKL which should be downloaded from Intel website (see [installation instructions](https://github.com/ikorotkin/dae-cpp#installation)).

If you build the examples using `cmake` (Linux/Mac) or `cmake-gui` (for Windows), make sure CMake is able to find the path to Intel MKL. It will find it automatically if MKL is installed with the default options. If CMake fails to find it, you need to provide the path to Intel MKL root directory manually using `DAE_MKL_DIR` option.

If you build the examples under Windows from Visual Studio directly, you should change the paths to MKL in the project properties in Visual Studio. In Solution Explorer window right-click on `dae-cpp`, then choose `Properties`, then `C/C++` -> `General`, change `Additional Include Directories` according to your paths. Same for `Librarian` -> `All Options` -> `Additional Library Directories`. Repeat procedure for each example. Fortunately, this should be done only once. Alternatively, you may use `cmake` for Windows, it should define all necessary paths for the Visual Studio project automatically.

If this doesn't help, can you please describe what you are doing, what OS you are using, what compiler?

**Comment by viviane-git** [comment]
Hi, 
I am using mac and I checked the path to the Intel MKL. It is in the default directory and still the MKLROOT variable cannot be found (see screenshot). Any ideas?

![Uploading Screenshot 2020-02-15 at 12.42.19.png…]()

**Comment by viviane-git** [comment]
Since the uploading did not work:
(base) Vivianes-MBP:build viviane$ cmake .. -DDAE_MKL_DIR=/opt/intel/mkl/
benchmarks/ bin/        examples/   include/    interfaces/ lib/        tools/      
(base) Vivianes-MBP:build viviane$ cmake .. -DDAE_MKL_DIR=/opt/intel/mkl/ -DCMAKE_INSTALL_PREFIX=/install_path
-- MKLROOT environment variable not found. Will use default MKL paths...
-- Apple OS detected...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/viviane/dae-cpp/build
(base) Vivianes-MBP:build viviane$

**Comment by ikorotkin** [comment]
Hi @viviane-git,

I tried a fresh installation of `dae-cpp` on mac and it does work for me...

"MKLROOT environment variable not found" is related to the environment variable defined in command line as

```bash
export MKLROOT="/opt/intel/mkl"
```

But from your message I see CMake didn't produce any errors, it successfully found MKL using default path, and found `include` directory as well. But then the compiler could not find `mkl_types.h` in there for some reason. Can you please check if `mkl_types.h` exists in `mkl/include/` directory?

I see a new version of Intel MKL was released recently, they might have changed something. I'll take a closer look into this. As a temporary workaround, can you try to install the previous, 2019 version of MKL and try again? That should work.
