### ISSUE TITLE
Plotting breaks cmake numpy issue

### ISSUE THREAD

**Issue by branch171** [ikorotkin/dae-cpp#22]
Hi I have installed.ok on Ubuntu 20.04 but if I switch Plotting ON in the CMakeList it gets an error I think due to python Numpy 
Library

it seems to find python 3.8.5 but numpy libraries aren’t found

any advice on how to fix this.

**Comment by ikorotkin** [comment]
Hi @branch171 

If `numpy` library cannot be found by `cmake` automatically, you can define the path manually using `cmake` option
`-DPYTHON_NUMPY_INCLUDE`,
where you need to provide a full path to `numpy/arrayobject.h` (do not include `/numpy/` in the path). For example, if the path is
`/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h`,
the option will be
`-DPYTHON_NUMPY_INCLUDE=/usr/local/lib/python3.6/dist-packages/numpy/core/include`

**Comment by branch171** [comment]
Hi I now have an issue with LIB_INTEL_MP not found. Is this some as well as MKL I need and how do I get it.

thanks

**Comment by branch171** [comment]
It is INTEL OPENMP

**Comment by branch171** [comment]
Hi I have it working now needed 

sudo apt install libomp-dev
