### ISSUE TITLE
compiling your own code

### ISSUE THREAD

**Issue by branch171** [ikorotkin/dae-cpp#24]
Hi, I have a successful install and ctests work. The question I have is how to you set up the compilation of a new program.

Do you use eclipse or visual code and if so how do you set all the include paths and dependencies for these.

Or do you use cmake? If so how do you do this for a  "cpp file" you have just made.

**Comment by ikorotkin** [comment]
It can be compiled in Eclipse, Visual Studio Code, and from the command line using cmake as well, doesn't matter.

I prefer Visual Studio Code, there is even an [example folder](https://github.com/ikorotkin/dae-cpp/tree/master/.vscode) `.vscode` that contains VS Code config files with all options, paths, etc. You can use them, just adjust the paths in the config files (at least for Python if you use plotting).

**Comment by ikorotkin** [comment]
A quick and dirty way to quickly compile your own cpp file would be renaming it to `robertson.cpp` and copying it to 
`dae-cpp/examples/robertson/` folder, then rebuild the examples following the instructions.
Just if you want to quickly check how it works.

**Comment by branch171** [comment]
Thanks I will check it out
